CI update

diff --git a/.github/workflows/nested_eagle.yml b/.github/workflows/nested_eagle.yml
--- a/.github/workflows/nested_eagle.yml
+++ b/.github/workflows/nested_eagle.yml
@@ -5,8 +5,8 @@ name: Nested Eagle CI Pipeline
 on:
   pull_request_review:
     types: [submitted]
-    paths: 
-      - 'nested_eagle/**' #only run for changes to nested eagle changes.
+    paths:
+      - "nested_eagle/**" #only run for changes to nested eagle changes.
 jobs:
   Submit_Grids:
     if: ${{ github.event.review.state == 'approved' && !contains(github.event.pull_request.labels.*.name, 'ci-running') }}
@@ -24,7 +24,7 @@ jobs:
       - name: Add a ci-running label
         uses: actions-ecosystem/action-add-labels@v1
         with:
-          labels: 'ci-running' # Adding ci-running label to prevent duplicate runs.
+          labels: "ci-running" # Adding ci-running label to prevent duplicate runs.
           github_token: ${{ secrets.GH_TOKEN }}
       - name: Submit Initial Grids
         run: |
@@ -61,6 +61,7 @@ jobs:
              done
              
              echo "Slurm jobs $JOB_ID1 and $JOB_ID2 to prepare the GFS & HRRR training data have completed."
+
   Run_Training:
     # The type of runner that the job will run on
     runs-on: ursa
@@ -134,30 +135,38 @@ jobs:
     # The type of runner that the job will run on
     runs-on: ursa
     timeout-minutes: 1440
-    needs: Perform_Inference_Postprocessing 
+    needs: Perform_Inference_Postprocessing
     steps:
-      - name: Perform verification with wxvx
+      - name: Perform grid2obs verification with wxvx
         run: |
-          cd nested_eagle/ursa/scientific_workflow/verification
+          cd $GITHUB_WORKSPACE/nested_eagle/ursa/scientific_workflow/verification/grid2obs
+          JOB_ID1=$(sbatch submit_obs_verification.sh | awk '{print $4}')
+          echo "Submitted Grid_to_Obs Verification Slurm job with ID: $JOB_ID1"
 
-          JOB_ID=$(sbatch submit_verification.sh | awk '{print $4}')
+          cd $GITHUB_WORKSPACE/nested_eagle/ursa/scientific_workflow/verification/grid2grid
+          JOB_ID2=$(sbatch submit_grid_verification.sh | awk '{print $4}')
+          echo "Submitted Grid_to_Grid Verification Slurm job with ID: $JOB_ID2"
 
-            echo "Submitted Verification Slurm job with ID: $JOB_ID"
-           
-            while squeue -h -j ${JOB_ID} | grep -q "${JOB_ID}"; do
-               squeue -j $JOB_ID
+          for JOB in $JOB_ID1 $JOB_ID2; do
+            echo "Waiting for job $JOB to complete..."
+            while squeue -h -j ${JOB} | grep -q "${JOB}"; do
+               squeue -j $JOB
                sleep 30  # Wait for 30 seconds before checking again.
             done
+            echo "Slurm job $JOB to perform verification has been completed."
 
-             echo "Slurm job $JOB_ID to perform verification has been completed."
+          cd $GITHUB_WORKSPACE/nested_eagle/ursa/scientific_workflow/verification/grid2obs/wxvx_workdir
+          find ./lam -name "*.png" -print -quit | grep -q . || { echo "Error: No LAM grid2obs verification plots found."; exit 1; } 
+          find ./global -name "*.png" -print -quit | grep -q . || { echo "Error: No global grid2obs verification plots found."; exit 1; } 
+          echo "Grid2obs Verification process has been successfully completed."
 
-             cd $GITHUB_WORKSPACE/nested_eagle/ursa/scientific_workflow/verification/wxvx_workdir
-             find ./lam -name "*.png" -print -quit | grep -q . || { echo "Error: No LAM verification plots found."; exit 1; } 
-             find ./global -name "*.png" -print -quit | grep -q . || { echo "Error: No global verification plots found."; exit 1; } 
-             echo "Verification process has been successfully completed."
-      - name: Remove label from pull request 
+          cd $GITHUB_WORKSPACE/nested_eagle/ursa/scientific_workflow/verification/grid2grid/wxvx_workdir
+          find ./lam -name "*.png" -print -quit | grep -q . || { echo "Error: No LAM grid2grid verification plots found."; exit 1; } 
+          find ./global -name "*.png" -print -quit | grep -q . || { echo "Error: No global grid2grid verification plots found."; exit 1; } 
+          echo "Grid2grid Verification process has been successfully completed."
+      - name: Remove label from pull request
         if: always()
         uses: mondeja/remove-labels-gh-action@v2.0.0
         with:
-          labels: 'ci-running'
+          labels: "ci-running"
           token: ${{ secrets.GH_TOKEN }}
